name: Run Tests and Security Scan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md" # Markdown dosyalarındaki değişiklikleri yoksay
  workflow_dispatch:

jobs:
  # Eğer PR'da push varsa ve aynı commit ise, gereksiz çalıştırmayı önle
  check-duplicate:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: "same_content"
          skip_after_successful_duplicate: "true"

  security-scan:
    needs: check-duplicate # Önce duplicate kontrolü yap
    if: ${{ needs.check-duplicate.outputs.should_skip != 'true' }}
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
